# Generated by Django 4.2.13 on 2024-06-24 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("address", models.CharField(max_length=200)),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.RemoveField(
            model_name="plannedservice",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="plannedservice",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="verificationcode",
            name="user",
        ),
        migrations.RemoveField(
            model_name="businessunit",
            name="revenue",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="business_units",
        ),
        migrations.DeleteModel(
            name="PastService",
        ),
        migrations.DeleteModel(
            name="PlannedService",
        ),
        migrations.DeleteModel(
            name="VerificationCode",
        ),
        migrations.AddField(
            model_name="businessdata",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app01.businessunit"
            ),
        ),
        migrations.AddField(
            model_name="businessdata",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app01.vendor"
            ),
        ),
    ]
