# Generated by Django 5.0.6 on 2024-07-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_restriction_restriction_fdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restriction',
        ),
    ]
