# Generated by Django 5.0.6 on 2024-07-21 17:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_restriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('restriction_id', models.CharField(primary_key=True, serialize=False)),
                ('restriction_street', models.CharField()),
                ('restriction_fstreet', models.CharField()),
                ('restriction_tstreet', models.CharField()),
                ('restriction_fdate', models.DateTimeField()),
                ('restriction_tdate', models.DateTimeField()),
                ('restriction_street_geometry', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('restriction_weekday', models.CharField()),
                ('restriction_ftime', models.TimeField()),
                ('restriction_ttime', models.TimeField()),
            ],
            options={
                'db_table': 'restrictions',
            },
        ),
    ]
